let g:skip_defaults_vim=1

"" " let g:netrw_sort_sequence=""
"" let g:netrw_special_syntax=1
"" " Netrw setting
"" let g:netrw_mousemaps= 0
"" " hide netrw menu
"" let g:netrw_banner = 0
"" " tree listing
"" let g:netrw_liststyle = 1
"" " open files in new tab
"" let g:netrw_browse_split = 0
"" let g:netrw_bufsettings="noma nomod nobl nowrap ro nu rnu"
"" let g:netrw_fastbrowse = 0
"" let g:netrw_list_hide = '^\.\.\/,^\.\/,^.svn/,^.git/'
"" let g:netrw_hide = 1
"" let g:netrw_dirhistmax = -1
"" let g:netrw_winsize = 25
"" let g:netrw_preview = 1
"" let g:netrw_alto = 0
"" let g:netrw_altfile = 1
"" let g:netrw_keepj = "keepj"
"" let g:netrw_sort_options = "i"

let g:lightline = {
      \ 'active': {
      \   'left': [ [ 'mode', 'paste' ],
      \             [ 'gitbranch', 'readonly', 'filename', 'modified' ] ]
      \ },
      \ 'component_function': {
      \   'gitbranch': 'gitbranch#name'
      \ },
      \ }

let g:vimfm_force_delete = 1
let g:vimfm_show_hidden_files = 1
let g:vimfm_linkid_str = '>'

silent! helptags ALL
set modelines=0
set nocompatible  
set viminfofile=NONE
colorscheme simozz
syntax enable
syntax sync fromstart

"set insertmode
set magic
set noautochdir
set noshowmode
set viminfo=""
set incsearch
filetype plugin on
syntax enable
" set syntax=auto
" set timeout timeoutlen=10 ttimeoutlen=1
set updatetime=4000
set notimeout
set nottimeout
set timeoutlen=50
set ttimeoutlen=50
" set tags=tags;/
" set tags=./tags,tags;
set tags=./tags;,tags
set noswapfile
set autoread
set autowrite
set clipboard=unnamed
" set guioptions+=a
" set guioptions-=m
" set guioptions-=T
" set guioptions+=a
" set guioptions+=h
" set guioptions-=b
" set guioptions-=r
" set guioptions-=R
" set guioptions-=l
" set guioptions-=L
" set guioptions+=e
" set guioptions=-l
set guioptions=""
set guioptions+=aepilr
set noscrollfocus
set virtualedit=onemore
set whichwrap=<,>,[,],b,s
set selection=exclusive
set selectmode=mouse,key
set keymodel=startsel,stopsel
set expandtab  
set autoindent
" set indentkeys+=!^I
" set smartindent
" set cindent
" set copyindent
set tabstop=4
set softtabstop=4
set shiftwidth=4
" set indentexpr=
set breakindent
set browsedir=current
set smarttab
set number 
set guifont=Monospace\ 10
set background=dark
set laststatus=2
set statusline=\ %{GetMode()}\ 
set statusline+=\ %=%{expand('%:p:~')}\ %y\ %m%r
set statusline+=\ b#%n,\ w#%{winnr()},\ t#%{tabpagenr()}
set statusline+=\ (%l\/\%L,\%c)\ 
set backspace=indent,eol,start
set guicursor=n:ver100-blinkoff0-nCursor
set guicursor+=o:ver100-blinkon250-blinkoff250-nCursor
set guicursor+=i:ver35-blinkon125-blinkoff125-iCursor
set guicursor+=v:ver35-blinkoff0-vCursor
set guicursor+=c-ci-cr:ver35-blinkoff0-cCursor

set noignorecase
set formatoptions=tcj
set mouse=ar
set encoding=utf-8
set nomousehide
" set mousefocus
set mouseshape=n:arrow,v:beam,i:beam
set mousemodel=popup
set lazyredraw
set scrolloff=0
set splitright
set splitbelow
set complete=.,t,w,b,d,k
set completeopt+=menuone,preview
set hidden
set hlsearch
set incsearch
set timeoutlen=0
set ttimeoutlen=0

set textwidth=0
set colorcolumn=0
set wrap
set linebreak
" note trailing space at end of next line

" set history=1000
" set wc=<Tab>
set wildmenu
set wildmode=full
set wildoptions+=pum
set showtabline=1
set guitabtooltip=%F
set guitablabel=%m\ %F
" set splitbelow
" set splitright
" tab sball
" set guiheadroom=0
set equalalways
" set iskeyword+=10,33-47,92-95
set cursorline
set showcmd
set bufhidden=hide
set switchbuf=useopen

" set showmatch
set nofoldenable
set foldmethod=indent
set foldnestmax=20
set foldcolumn=0
set fillchars=stl:\ ,stlnc:\ ,vert:\|,fold:\ ,diff:-

set diffopt=internal,filler,closeoff,vertical

" set undodir=/tmp/
" set undofile

set list
set listchars=tab:>\  

" set tabpanelopt=columns:16,align:right
" set tabpanelopt=vert,align:right
" set tabpanelopt=columns:16
" set tabpanel=%!TestTabBuflist()
" set showtabpanel=1

let g:bclose_multiple = 0
let g:searchString = ''
let g:loaded_table_mode = '0'

augroup BufWinIn
   autocmd!
   autocmd BufEnter * if ((&ft != "help") 
                      \ && (&ft != "netrw")
                      \ && (&ft != "vimfm")) |  
                      \ startinsert |  
                      \ endif
   autocmd BufAdd,BufCreate,BufNewFile * silent! call AddFtDict()
augroup end

augroup Insert
   autocmd!
   autocmd InsertEnter * set nohlsearch
   autocmd InsertLeave * set hlsearch
   " autocmd KeyInputPre * if v:char == 28 | let v:char = 92 | endif
   " autocmd InsertLeave * set iminsert=0
   " autocmd InsertEnter * set iminsert=1
   " autocmd InsertEnter * let @*=""
   " autocmd CompleteDonePre * if complete_info()['selected'] >= 0 &&
                             \ getline('.')[col('.'):] =~ '\w' |
                             \ silent! normal! ved | 
                             \ endif
augroup END

augroup Vim
   autocmd!
   autocmd VimEnter * packloadall!
   autocmd GUIEnter * call system('wmctrl -i -b add,maximized_vert,maximized_horz -r '.v:windowid)
   autocmd VimEnter * if (argv(0) == '' || argv(0) == '.') |
                      \ call SetPWD($PWD) | :Vimfm |
                      \ elseif (isdirectory(argv(0))) |
                      \ call SetPWD(argv(0)) | 
                      \ else |
                      \ call SetPWD(expand("%:h")) |
                      \ endif
   autocmd VimEnter * call AutoCompleteInoremap()
   autocmd TabNew * :$tabmove
   "" autocmd VimEnter * if filereadable(GetPWD().'tags') | exec 'set tags+='.GetPWD().'/tags' | endif
   "" autocmd DirChanged * if filereadable(GetCWD().'tags') | exec 'set tags+='.GetCWD().'/tags' | endif
   autocmd VimEnter,ModeChanged * call SetCursorLineMode() | call SetStatusLineMode()
   autocmd CursorMoved,CursorMovedI * silent! call HighlightWordUnderCursor()

   " Trigger relative number when entering visual mode,
   autocmd ModeChanged [nvV\x16]*:* let &l:rnu = mode() =~# '^[nvV\x16]'
   " Trigger norelative number when leaving visual mode
   autocmd ModeChanged *:[nvV\x16]* let &l:rnu = mode() =~# '^[nvV\x16]'
   " autocmd CmdlineLeavePre * if char2nr(v:char) == 13 && getcmdtype() == ':' && getcmdline()[0:1] == '%s' && stridx(getcmdline(), '\/g') != -1 | stridx(getcmdline(), ' | normal! g``') == -1 | call setcmdline(getcmdline().' | normal! g``') | endif
augroup END

augroup AutoFoldColumn
  au!
  au CursorHold,BufWinEnter,WinEnter * AutoOrigamiFoldColumn
augroup END

" inoremap <silent> <nowait> <C-r> <C-r><C-o>

" Bug fix in case of wrong \ interpretation
inoremap <silent> <nowait> <C-\> \
snoremap <silent> <nowait> <C-\> \
nnoremap <silent> <nowait> <C-\> \
snoremap <silent> <nowait> <C-\> \
vnoremap <silent> <nowait> <C-\> \
cnoremap <nowait> <C-\> \

snoremap <silent> <nowait> <kPlus> i
snoremap <silent> <nowait> <kMinus> <Esc>-


inoremap <expr> <silent> <nowait> <Down> pumvisible() ? "<Down>" : "<C-o>gj"
inoremap <expr> <silent> <nowait> <Up> pumvisible() ? "<Up>" : "<C-o>gk"
nnoremap <silent> <nowait> j gj
nnoremap <silent> <nowait> <Down> gj
nnoremap <silent> <nowait> k gk
nnoremap <silent> <nowait> <Up> gk

"inoremap <silent> <nowait> <expr> <Backspace> getline('.')[col('.')-2] == '\s\+' ? "<Backspace><Backspace><Backspace>" : "<Backspace>"

inoremap <silent> <nowait> <C-ScrollWheelUp> <C-o>:call LargerFont()<CR>
" inoremap <silent> <nowait> <C-RightRelease> <C-o>:call LargerFont()<CR>
inoremap <silent> <nowait> <C-ScrollWheelDown> <C-o>:call SmallerFont()<CR>
" inoremap <silent> <nowait> <C-LeftRelease> <C-o>:call SmallerFont()<CR>
nnoremap <silent> <nowait> <C-ScrollWheelUp> :call LargerFont() <CR>
" nnoremap <silent> <nowait> <C-RightRelease> :call LargerFont()<CR>
nnoremap <silent> <nowait> <C-ScrollWheelDown> :call SmallerFont()<CR>
" nnoremap <silent> <nowait> <C-LeftRelease> :call SmallerFont()<CR>

" Scroll bar right
inoremap <silent> <nowait> <M-PageUp> <C-o>10zh
nnoremap <silent> <nowait> <M-PageUp> 10zh
xnoremap <silent> <nowait> <M-PageUp> 10zh
inoremap <silent> <nowait> <C-M-ScrollWheelUp> <C-o>10zh:
nnoremap <silent> <nowait> <C-M-ScrollWheelUp> 10zh
snoremap <silent> <nowait> <C-M-ScrollWheelUp> <C-o>10zh

" Scroll bar left
inoremap <silent> <nowait> <M-PageDown> <C-o>10zl
nnoremap <silent> <nowait> <M-PageDown> 10zl
xnoremap <silent> <nowait> <M-PageDown> 10zl
inoremap <silent> <nowait> <C-M-ScrollWheelDown> <C-o>10zl
nnoremap <silent> <nowait> <C-M-ScrollWheelDown> 10zl
snoremap <silent> <nowait> <C-M-ScrollWheelDown> <C-o>10zl

" C-o: goes to normal mode if insert mode. This makes less likely
" to accidentally jump from insert and normal mode
" inoremap <silent> <nowait> <C-o> <Esc>l
nnoremap <silent> <nowait> <C-o> <nop>

" Esc: return to normal mode if insert mode, or viceversa
" inoremap <silent> <nowait> <Esc> <C-o><Esc>
" inoremap <silent> <nowait> <expr> <Esc> col('.')== 1? "<Esc>" : "<Esc><Right>"
inoremap <silent> <nowait> <C-c> <nop>
cnoremap <expr> <silent> <nowait> <CR> getcmdtype() == '/' ? "<CR>zz" : "<CR>"

" C-M-Enter: start visual block mode
inoremap <silent> <nowait> <C-Space> <Esc>viw
nnoremap <silent> <nowait> <C-Space> viw
xnoremap <expr> <silent> <nowait> <C-Space> mode() == "v" ? "V" : "v"

inoremap <expr> <silent> <nowait> <Esc> col('.') != 1 ? "<Esc><Right>" : "<Esc>"
vnoremap <silent> <nowait> <Esc> <Esc>i
nnoremap <silent> <nowait> <Esc> i
nnoremap <silent> <nowait> <M-n> i

" M-w: Change window
inoremap <silent> <nowait> <M-w> <C-o><C-w><C-w>
nnoremap <silent> <nowait> <M-w> <C-w><C-w>

" C-d: open netrw in a new tab 
inoremap <silent> <nowait> <C-d> <C-c>:VimfmCurDir<CR>
nnoremap <silent> <nowait> <C-d> :VimfmCurDir<CR>
vnoremap <silent> <nowait> <C-d> <Esc><C-o>:VimfmCurDir<CR>
snoremap <silent> <nowait> <C-d> <Esc><C-o>:VimfmCurDir<CR>
cnoremap <silent> <nowait> <C-d> <C-c>:VimfmCurDir<CR>

" inoremap <expr> <nowait> <F1> len(expand('<cword>')) > 0 ? "<C-c>:h <C-r><C-w><CR>" : "<C-c>:h "
" nnoremap <expr> <nowait> <F1> len(expand('<cword>')) > 0 ? ":h <C-r><C-w><CR>" : ":h "
vnoremap <nowait> <F1> <C-c>:h <C-r>*<CR>

" F2 mappings
inoremap <silent> <nowait> <F2> <C-o>:call LargerFont()<CR>
nnoremap <silent> <nowait> <F2> :call LargerFont()<CR>

" F3: switch to next window
inoremap <silent> <nowait> <S-F2> <C-o>:call SmallerFont()<CR>
nnoremap <silent> <nowait> <S-F2> :call SmallerFont()<CR>

" F4: open file to diff side by side
inoremap <nowait> <M-d> <C-o>:vert diffsplit 
nnoremap <nowait> <M-d> <C-o>:vert diffsplit 

" M-S-d: diffoff
inoremap <silent> <nowait> <M-S-d> <C-o>:diffoff<CR>
nnoremap <silent> <nowait> <M-S-d> <C-o>:diffoff<CR>

" F5: increase vertical resize by 5 units
" inoremap <silent> <nowait> <F5> <C-o>:vertical resize +5<CR>
" nnoremap <silent> <nowait> <F5> :vertical resize +5<CR>

" inoremap <silent> <nowait> <F5> <C-o>:vertical resize +5<CR>
" nnoremap <silent> <nowait> <F5> :vertical resize +5<CR>

inoremap <silent> <nowait> <F5> <C-o>:source ${MYGVIMRC}<CR><C-o>:redraw<CR>
nnoremap <silent> <nowait> <F5> :source ${MYGVIMRC}<CR>:redraw<CR>

" S-F5: descrease vertical resize by 5 units
" inoremap <silent> <nowait> <S-F5> <C-o>:vertical resize -5<CR>
" nnoremap <silent> <nowait> <S-F5> :vertical resize -5<CR>

" F6: Turn off hlsearch highlight
inoremap <silent> <nowait> <F6> <C-o>:set nohlsearch<CR>
nnoremap <silent> <nowait> <F6> :set nohlsearch<CR>

" F7 to F9 <nop>
" noremap <silent> <nowait> <F7> <C-o>:set relativenumber!<CR>
inoremap <silent> <nowait> <F7> <nop>
nnoremap <silent> <nowait> <F7> <nop>
inoremap <silent> <nowait> <F8> <nop>
nnoremap <silent> <nowait> <F8> <nop>
inoremap <silent> <nowait> <F9> <nop>
inoremap <silent> <nowait> <F9> <nop>
nnoremap <silent> <nowait> <F9> <nop>
inoremap <silent> <nowait> <F10> <nop>
nnoremap <silent> <nowait> <F10> <nop>
inoremap <silent> <nowait> <F12> <nop>
nnoremap <silent> <nowait> <F12> <nop>
" vnoremap <silent> <nowait> <F7> <C-o>:set relativenumber!<CR>
vnoremap <silent> <nowait> <F7> <nop>
vnoremap <silent> <nowait> <F8> <Esc>
vnoremap <silent> <nowait> <F9> <Esc>
vnoremap <silent> <nowait> <F9> <Esc>
"vnoremap <expr> <silent> <nowait> <F11> (&columns <= 100) ? "<Esc>:set columns=999<CR>" : "<Esc>:set columns=171<CR>"
vnoremap <silent> <nowait> <F12> <nop>
" snoremap <silent> <nowait> <F7> <C-o>:set relativenumber!<CR>
snoremap <silent> <nowait> <F7> <nop>
snoremap <silent> <nowait> <F8> <Esc>
snoremap <silent> <nowait> <F9> <Esc>
snoremap <silent> <nowait> <F9> <Esc>
" snoremap <expr> <silent> <nowait> <F11> (&columns <= 100) ? "<Esc>:set columns=999<CR>" : "<Esc>:set columns=171<CR>"
snoremap <silent> <nowait> <F12> <nop>

" F11: toggle full screen
" inoremap <expr> <silent> <nowait> <F11> (&columns <= 100) ? "<C-o>:set columns=999<CR>" : "<C-o>:set columns=171<CR>"
" nnoremap <expr> <silent> <nowait> <F11> (&columns <= 100) ? "<C-o>:set columns=999<CR>" : "<C-o>:set columns=171<CR>"

" <Home>: jump before the first non-blank of the current line, or at the first
" column
inoremap <expr> <silent> <nowait> <Home> col('.') == 1 ? "<C-o>^" : "<C-o>0"
nnoremap <expr> <silent> <nowait> <Home> col('.') == 1 ? "^" : "0"
vnoremap <expr> <silent> <nowait> <Home> col('.') == 1 ? "^" : "0"
snoremap <expr> <silent> <nowait> <S-Home> col('.') == 1 ? "<C-o>^" : "<C-o>0"

inoremap <silent> <nowait> <M-p> <C-o>:exec ":cd ".expand("%:h")<CR>
nnoremap <silent> <nowait> <M-p> :exec ":cd ".expand("%:h")<CR>
vnoremap <silent> <nowait> <M-p> <Esc><C-c>:exec ":cd ".expand("%:h")<CR>

inoremap <C-j> <C-o><C-w><C-]>
inoremap <C-2-LeftMouse> <LeftMouse><C-o><C-w><C-]>
nnoremap <C-j> <C-w><C-]>
nnoremap <C-2-LeftMouse> <LeftMouse><C-w><C-]>
vnoremap <C-j> <C-w><C-]>

" Indent code
inoremap <nowait> <M-i> <C-o>:call Indent()<CR>
nnoremap <nowait> <M-i> :call Indent()<CR>
snoremap <nowait> <M-i> <C-o>:call Indent()<CR>

" C-c: command line mode
inoremap <nowait> <M-x> <C-o>:
nnoremap <nowait> <M-x> :
snoremap <nowait> <M-x> <C-o>:
xnoremap <nowait> <M-x> <C-c>:'<,'>
" tnoremap <silent> <nowait> <Esc> <C-\><C-n>
cnoremap <nowait> <M-x> <C-c>:

inoremap <silent> <nowait> <C-LeftMouse> <C-o><C-w><C-]>
inoremap <silent> <nowait> <C-RightMouse> <nop>
nnoremap <silent> <nowait> <C-LeftMouse> <LeftMouse><C-w><C-]>
nnoremap <silent> <nowait> <C-RightMouse> <nop>

" S-Del
inoremap <silent> <nowait> <S-Del> <nop>
cnoremap <silent> <nowait> <S-Del> <nop>

inoremap <expr> <silent> <nowait> <CR> pumvisible() ? "<C-y>" : "<CR>"
inoremap <expr> <silent> <nowait> <LeftMouse> pumvisible() ? "<C-y>" : "<LeftMouse>"

" Tab: advance completition selection if pumvisible, Tab otherwise
inoremap <expr> <silent> <nowait> <Tab> pumvisible() != 0 ? "<C-n>" : getline('.') == "" ? "<C-o>:call JumpToPrevIndent()<CR>" : "<Tab>"
nnoremap <silent> <nowait> <Tab> >>

" S-Tab: de-advance completition selection if pumvisible, inverse Tab otherwise
inoremap <expr> <silent> <nowait> <S-Tab> pumvisible() != 0 ? "<C-p>" : "<C-d>"
nnoremap <silent> <nowait> <S-Tab> <<

"inoremap <silent> <nowait> <C-Enter> <C-o>n
"nnoremap <silent> <nowait> <C-Enter> n

"inoremap <silent> <nowait> <C-M-Enter> <C-o>#
"nnoremap <silent> <nowait> <C-M-Enter> #

inoremap <silent> <nowait> <C-q> <C-o><C-q>

inoremap <nowait> <C-f> <Esc>/
nnoremap <nowait> <C-f> /
xnoremap <nowait> <C-f> <C-c>:%s/<C-r>=AdjStr('*')<CR>//gn<CR>
snoremap <nowait> <C-f> <C-c>:%s/<C-r>=AdjStr('*')<CR>//gn<CR>
cnoremap <silent> <nowait> <C-f> /<C-r>/<CR>nzz
cnoremap <nowait> <C-w> <C-r><C-w>

inoremap <nowait> <C-S-f> <C-o>:find **/
nnoremap <nowait> <C-S-f> :find **/
vnoremap <nowait> <C-S-f> <Esc>:find **/
cnoremap <nowait> <C-S-f> :find **/

inoremap <nowait> <C-h> <C-o>:%s/<C-r><C-w>/
nnoremap <nowait> <C-h> :%s/<C-r><C-w>/
vnoremap <nowait> <C-h> <Esc><C-c>:%s/<C-r>=AdjStr('*')<CR>/
cnoremap <silent> <nowait> <C-h> <C-c>

" inoremap <nowait> <C-h> <C-o>:call Replace("<C-r><C-w>", 1)<CR>
" nnoremap <nowait> <C-h> :call Replace("<C-r><C-w>")<CR>
" xnoremap <nowait> <C-h> <C-c>:call Replace(getreg('*'), 0)<CR>
" snoremap <nowait> <C-h> <C-c>:call Replace(getreg('*'), 0)<CR>
" cnoremap <silent> <nowait> <C-h> <C-c>

inoremap <silent> <nowait> <C-M-h> <C-o>:call setreg('/', '')<CR>
nnoremap <silent> <nowait> <C-M-h> :call setreg('/', '')<CR>
vnoremap <silent> <nowait> <C-M-h> <Esc><C-c>:call setreg('/', '')<CR>
cnoremap <silent> <nowait> <C-M-h> <C-c>:call setreg('/', '')<CR>

cnoremap <nowait> <C-w> <C-r><C-w>

vnoremap <nowait> <C-S-f> <C-o>?<CR>
nnoremap <nowait> <C-M-Backspace> ?<CR>

" C-.: toggle code fol=ding
inoremap <silent> <nowait> <C-.> <C-o>zc<C-o>zz
nnoremap <silent> <nowait> <C-.> zczz
xnoremap <silent> <nowait> <C-.> <Esc><C-c>zFzz
snoremap <silent> <nowait> <C-.> <C-o>zFzz

" Copy
vnoremap <silent> <nowait> <C-c> "+ygv
" C-v: Paste
inoremap <nowait> <C-v> <C-r><C-o>+
nnoremap <nowait> <C-v> i<C-r><C-o>+<Esc>
" vnoremap <nowait> <C-v> <C-r><C-o>+
cnoremap <nowait> <C-v> <C-r>+
cnoremap <nowait> <C-S-v> <C-r>=AdjStr('+')<CR>

vnoremap <silent> <nowait> <C-v> "+P

inoremap <nowait> <C-M-v> <C-o>:set paste<CR><C-r>+<C-o>:set nopaste<CR>
nnoremap <nowait> <C-M-v> :set paste<CR><C-r>+:set nopaste<CR>
vnoremap <nowait> <C-M-v> <Esc>:set paste<CR><C-r>+:set nopaste<CR>

" C-l: prompt replace
inoremap <nowait> <C-l> <C-o>:call BufferList()<CR>
nnoremap <nowait> <C-l> :call BufferList()<CR>
snoremap <nowait> <C-l> <C-o>:call BufferList()<CR>
" inoremap <nowait> <C-l> <C-o>:FuzzyBuffers<CR>
" nnoremap <nowait> <C-l> :FuzzyBuffers<CR>
" snoremap <nowait> <C-l> <C-o>:FuzzyBuffers<CR>

" inoremap <nowait> <M-l> <C-o>:FuzzyFiles<CR>
" nnoremap <nowait> <M-l> :FuzzyFiles<CR>
" snoremap <nowait> <M-l> <C-o>:FuzzyFiles<CR>

" C-s: save
inoremap <nowait> <C-s> <Cmd>:call GuiSave()<CR>
nnoremap <nowait> <C-s> :call GuiSave()<CR>
xnoremap <nowait> <C-s> <Cmd>:call GuiSave()<CR>
snoremap <nowait> <C-s> <Cmd>:call GuiSave()<CR>
cnoremap <nowait> <C-s> <Esc>

" C-k: delete line
inoremap <silent> <nowait> <C-k> <C-o>dd
nnoremap <silent> <nowait> <C-k> dd
vnoremap <silent> <nowait> <C-k> <Delete>

" C-g: go to line and column
inoremap <silent> <nowait> <C-g> <C-o>:call GoToLineIntractv()<CR>
nnoremap <silent> <nowait> <C-g> :call GoToLineIntractv()<CR>
xnoremap <silent> <nowait> <C-g> <Esc>:call GoToLineIntractv()<CR>
snoremap <silent> <nowait> <C-g> <Esc>:call GoToLineIntractv()<CR>

inoremap <nowait> <C-b> <C-o>:b 
nnoremap <nowait> <C-b> :b 
vnoremap <nowait> <C-b> <Esc>:b 

inoremap <nowait> <C-M-b> <C-o>:b<Space>
nnoremap <nowait> <C-M-b> :b<Space>
vnoremap <nowait> <C-M-b> <Esc>:b<Space>

inoremap <nowait> <M-b> <C-o><C-6>
nnoremap <nowait> <M-b> <C-6>
vnoremap <nowait> <M-b> <Esc><C-6>

" C-z: undo changes
inoremap <silent> <nowait> <C-z> <C-o>:undo<CR>
nnoremap <silent> <nowait> <C-z> :undo<CR>
snoremap <silent> <nowait> <C-z> <Esc><Esc>:undo<CR>
vnoremap <silent> <nowait> <C-z> <Esc><Esc>:undo<CR>

" C-y: redo changes
inoremap <silent> <nowait> <C-y> <C-o>:redo<CR>
nnoremap <silent> <nowait> <C-y> :redo<CR>
xnoremap <silent> <nowait> <C-z> <Esc>:redo<CR>

" MiddleMouse: paste as well
inoremap <silent> <nowait> <MiddleMouse> <nop>
nnoremap <silent> <nowait> <MiddleMouse> <nop>
vnoremap <silent> <nowait> <MiddleMouse> <nop>

" M-s: select inner word
inoremap <silent> <nowait> <M-s> <Esc>viw<C-g>
nnoremap <silent> <nowait> <M-s> viw
xnoremap <silent> <nowait> <M-s> iw
snoremap <silent> <nowait> <M-s> <C-g>iw<C-g>

inoremap <silent> <nowait> <C-e> <C-o>:enew!<CR>
nnoremap <silent> <nowait> <C-e> :enew!<CR>
vnoremap <silent> <nowait> <C-e> <Esc><Esc>:enew!<CR>

" C-a: select all
inoremap <silent> <nowait> <C-a> <Esc>ggVG
nnoremap <silent> <nowait> <C-a> ggVG

" C-n
inoremap <silent> <nowait> <C-n> <C-o>:vsplit<CR>
nnoremap <silent> <nowait> <C-n> :vsplit<CR>
vnoremap <silent> <nowait> <C-n> <Esc>:vsplit<CR><Esc>
"snoremap <silent> <nowait> <C-n> <Esc><C-o>:vsplit<CR>

" C-M-n
inoremap <silent> <nowait> <C-M-n> <C-o>:split<CR>
nnoremap <silent> <nowait> <C-M-n> :split<CR>
vnoremap <silent> <nowait> <C-M-n> <Esc>:split<CR><Esc>
"snoremap <silent> <nowait> <C-n> <C-o>:split<CR>

" C-PageUp: switch to next window or tab
inoremap <expr> <silent> <nowait> <C-PageUp> winnr() > 1 ? "<C-o>:call GoToPrevWin()<CR>" : "<C-o>:tabprev<CR>"
nnoremap <expr> <silent> <nowait> <C-PageUp> winnr() > 1 ? ":call GoToPrevWin()<CR>" : ":tabprev<CR>"
xnoremap <expr> <silent> <nowait> <C-PageUp> winnr() > 1 ? "<Esc>:call GoToPrevWin()<CR>" : "<Esc>:tabprev<CR>"
" inoremap <silent> <nowait> <C-PageUp> <C-o>:call GoToPrevWin()<CR>
" nnoremap <silent> <nowait> <C-PageUp> :call GoToPrevWin()<CR>
" xnoremap <silent> <nowait> <C-PageUp> <Esc>:call GoToPrevWin()<CR>
" cnoremap <silent> <nowait> <C-PageUp> <Esc>

" C-PageDown: switch to previous window or tab
inoremap <expr> <silent> <nowait> <C-PageDown> winnr() < winnr('$') ? "<C-o>:call GoToNextWin()<CR>" : "<C-o>:tabnext<CR>"
nnoremap <expr> <silent> <nowait> <C-PageDown> winnr() < winnr('$') ? ":call GoToNextWin()<CR>" : ":tabnext<CR>"
xnoremap <expr> <silent> <nowait> <C-PageDown> winnr() < winnr('$') ? "<Esc>:call GoToNextWin()<CR>" : "<Esc>:tabnext<CR>"
" inoremap <silent> <nowait> <C-PageDown> <C-o>:call GoToNextWin()<CR>
" nnoremap <silent> <nowait> <C-PageDown> :call GoToNextWin()<CR>
" xnoremap <silent> <nowait> <C-PageDown> <Esc>:call GoToNextWin()<CR>
" cnoremap <silent> <nowait> <C-PageDown> <Esc>

" inoremap <silent> <nowait> <M-w> <C-o>:call GoToWin()<CR>
" nnoremap <silent> <nowait> <M-w> :call GoToWin()<CR>
" vnoremap <silent> <nowait> <M-w> <C-o>:call GoToWin()<CR>
" cnoremap <silent> <nowait> <-w> <C-c>

" M-o: open pop up window to open a file (or create one)
inoremap <silent> <nowait> <M-o> <C-o>:browse confirm e<CR>
nnoremap <silent> <nowait> <M-o> :browse confirm e<CR>
                            
" Better advance or reverse page
inoremap <expr> <silent> <nowait> <PageDown> pumvisible() ? "<Down>" : "<C-o>:call PageDown()<CR>"
nnoremap <silent> <nowait> <PageDown> :call PageDown()<CR>
snoremap <silent> <nowait> <PageDown> <C-o>:call PageDown()<CR>

inoremap <expr> <silent> <nowait> <PageUp> pumvisible() ? "<Up>" : "<C-o>:call PageUp()<CR>"
nnoremap <silent> <nowait> <PageUp> :call PageUp()<CR>
snoremap <silent> <nowait> <PageUp> <C-o>:call PageUp()<CR>

" C-Up: 
" inoremap <silent> <nowait> <C-Up> <C-o>:call BetterBufferPrev()<CR>
" nnoremap <silent> <nowait> <C-Up> :call BetterBufferPrev()<CR>
" vnoremap <silent> <nowait> <C-Up> <Esc><C-o>:call BetterBufferPrev()<CR>

" C-Down:
" inoremap <silent> <nowait> <C-Down> <C-o>:call BetterBufferNext()<CR>
" nnoremap <silent> <nowait> <C-Down> :call BetterBufferNext()<CR>
" vnoremap <silent> <nowait> <C-Down> <Esc><C-o>:call BetterBufferNext()<CR>


" C-Right: forward word movement
inoremap <expr> <silent> <nowait> <C-Right> getline('.')[col('.')-1] == ' ' ? "<C-o>w" : "<C-o>e<Right>"
nnoremap <expr> <silent> <nowait> <C-Right> getline('.')[col('.')-1] == ' ' ? "w" : "e<Right>"
" C-Left: Backward word movement
inoremap <expr> <silent> <nowait> <C-Left> getline('.')[col('.')-2] == ' ' ? "<C-o>ge<Right>" : "<C-o>b"
nnoremap <expr> <silent> <nowait> <C-Left> getline('.')[col('.')-2] == ' ' ? "ge<Right>" : "b"

" C-x: close current buffer
inoremap <silent> <nowait> <C-x> <C-o>:call CloseBuffer()<CR>
nnoremap <silent> <nowait> <C-x> :call CloseBuffer()<CR>
" tnoremap <silent> <nowait> <C-x> exit<CR>

inoremap <silent> <nowait> <C-w> <C-o><C-w>
inoremap <silent> <nowait> <C-S-x> <C-o><C-w>c
nnoremap <silent> <nowait> <C-S-x> <C-w>c

vnoremap <silent> <nowait> + <C-a>
vnoremap <silent> <nowait> <kPlus> <C-a>
vnoremap <silent> <nowait> - <C-x>
vnoremap <silent> <nowait> <kMinus> <C-x>

" C-t: open new tab
inoremap <expr> <silent> <nowait> <C-S-t> expand('%') == '' ? "<C-o>:tabnew<CR>" : "<C-o>:tabnew %<CR>"
nnoremap <expr> <silent> <nowait> <C-S-t> expand('%') == '' ? ":tabnew<CR>" : ":tabnew %<CR>"
snoremap <expr> <silent> <nowait> <C-S-t> expand('%') == '' ? "<Esc>:tabnew<CR>" : "<Esc>:tabnew %<CR>"
vnoremap <expr> <silent> <nowait> <C-S-t> expand('%') == '' ? "<Esc>:tabnew<CR>" : "<Esc>:tabnew %<CR>"

" C-Del
inoremap <expr> <silent> <nowait> <C-Del> (col('.')-1)==strlen(getline('.')) ? "<Del>" : "<C-o>dw"
nnoremap <silent> <nowait> <C-Del> dw

" C-Backspace
inoremap <silent> <nowait> <C-Backspace> <C-o>db
nnoremap <silent> <nowait> <C-Backspace> db
cnoremap <nowait> <C-Backspace> <C-w>

" End: go to end of line
nnoremap <silent> <nowait> <End> $<Right>
snoremap <silent> <nowait> <End> <Esc>$
xnoremap <silent> <nowait> <End> $

" <ScrollWheelUp> <ScrollWheelDown>
inoremap <silent> <nowait> <expr> <ScrollWheelUp> pumvisible() ? "<Up>" : "<C-o>:call ScrollWheelUp(winheight('.')/6)<CR>"
inoremap <silent> <nowait> <expr> <ScrollWheelDown> pumvisible() ? "<Down>" : "<C-o>:call ScrollWheelDown(winheight('.')/6)<CR>"
nnoremap <silent> <nowait> <ScrollWheelUp> :call ScrollWheelUp(winheight('.')/6)<CR>
nnoremap <silent> <nowait> <ScrollWheelDown> :call ScrollWheelDown(winheight('.')/6)<CR>
xnoremap <silent> <nowait> <ScrollWheelUp> <C-c>:call ScrollWheelUp(winheight('.')/6)<CR>
xnoremap <silent> <nowait> <ScrollWheelDown> <C-c>:call ScrollWheelUp(winheight('.')/6)<CR>

vnoremap <silent> <nowait> <M-v> <nop>
xnoremap <silent> <nowait> <Up> k
xnoremap <silent> <nowait> <Down> j
xnoremap <silent> <nowait> <Left> h
xnoremap <silent> <nowait> <Right> l
" vnoremap <silent> <nowait> <C-Space> w
xnoremap <silent> <nowait> <Backspace> d
" snoremap <silent> <nowait> <Backspace> d
vnoremap <silent> <nowait> <C-Backspace> b
vnoremap <silent> <nowait> <C-z> u
vnoremap <silent> <nowait> <Tab> >gv
vnoremap <silent> <nowait> <S-Tab> <gv

" tnoremap <silent> <nowait> <C-c> <C-\><C-n><C-w>N<C-\><C-n>

vnoremap <silent> <nowait> <C-k> Vd
vnoremap <silent> <nowait> <M-o> <nop>
" snoremap <silent> <nowait> <M-w> <C-o><C-w>w

" Enclose word by {} [] () "" if visual selected
xnoremap <silent> <nowait> [ di[<C-r><C-o>*]
xnoremap <silent> <nowait> { di{<C-r><C-o>*}
xnoremap <silent> <nowait> ( di(<C-r><C-o>*)
xnoremap <silent> <nowait> ] di[<C-r><C-o>*]
xnoremap <silent> <nowait> } di{<C-r><C-o>*}
xnoremap <silent> <nowait> ) di(<C-r><C-o>*)
xnoremap <silent> <nowait> " "<C-r><C-o>*"

" Enclose word by {} [] () "" if selected
snoremap <silent> <nowait> { {<C-r><C-o>*}
snoremap <silent> <nowait> [ [<C-r><C-o>*]
snoremap <silent> <nowait> ( (<C-r><C-o>*)
snoremap <silent> <nowait> } {<C-r><C-o>*}
snoremap <silent> <nowait> ] [<C-r><C-o>*]
snoremap <silent> <nowait> ) (<C-r><C-o>*)
snoremap <silent> <nowait> " "<C-r><C-o>*"

vnoremap <silent> <nowait> <ScrollWheelUp> <Esc>
snoremap <silent> <nowait> <ScrollWheelUp> <Esc>
vnoremap <silent> <nowait> <ScrollWheelDown> <Esc>
snoremap <silent> <nowait> <ScrollWheelDown> <Esc>

" C-S-Right/Left: select word under cursor
inoremap <silent> <nowait> <C-S-Right> <S-Right>e<C-g>
inoremap <silent> <nowait> <C-S-Left>  <S-Left>b<C-g>
vnoremap <expr> <silent> <nowait> <C-S-Right> getline('.')[col('.')-1] == ' ' ? "w" : "e"
vnoremap <expr> <silent> <nowait> <C-S-Left> getline('.')[col('.')-2] == ' ' ? "gel" : "b"

